name: TreeExporter
description: Generate repository structure visualization
author: mrf0rtuna4
inputs:

  path:
    description: Repository path
    required: false
    default: "."

  output:
    description: Output file
    required: false
    default: "structure.txt"

  format:
    description: Export format
    required: false
    default: "txt"

  exclude:
    description: Additional excluded folders separated by comma
    required: false
    default: ""

  commit:
    default: "false"

  commit-message:
    default: "Update repository structure"

  branch:
    default: ""

runs:

  using: docker
  image: Dockerfile

  args:
    - --path
    - ${{ inputs.path }}
    - --output
    - ${{ inputs.output }}
    - --format
    - ${{ inputs.format }}
    - --exclude
    - ${{ inputs.exclude }}